// Code generated by go-vk from vk.xml at 2023-01-14 10:53:48.4373753 -0600 CST m=+1.128672301. DO NOT EDIT.
package vk

import "unsafe"

// DeviceAddress: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkDeviceAddress.html
type DeviceAddress uint64

// DeviceSize: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkDeviceSize.html
type DeviceSize uint64

// Flags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkFlags.html
type Flags uint32

// PFN_vkAllocationFunction: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/PFN_vkAllocationFunction.html
type PFN_vkAllocationFunction unsafe.Pointer

// PFN_vkFreeFunction: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/PFN_vkFreeFunction.html
type PFN_vkFreeFunction unsafe.Pointer

// PFN_vkInternalAllocationNotification: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/PFN_vkInternalAllocationNotification.html
type PFN_vkInternalAllocationNotification unsafe.Pointer

// PFN_vkInternalFreeNotification: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/PFN_vkInternalFreeNotification.html
type PFN_vkInternalFreeNotification unsafe.Pointer

// PFN_vkReallocationFunction: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/PFN_vkReallocationFunction.html
type PFN_vkReallocationFunction unsafe.Pointer

// PFN_vkVoidFunction: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/PFN_vkVoidFunction.html
type PFN_vkVoidFunction unsafe.Pointer

// SampleMask: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkSampleMask.html
type SampleMask uint32

// Bool32: Note that go-vk uses standard Go bools throughout the public API. Bool32 is only used internally and is automatically translated for you.
// See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkBool32.html
type Bool32 uint32
