//go:build darwin
// Code generated by go-vk from vk-1.3.242.xml at 2023-03-31 10:23:49.2859083 -0500 CDT m=+3.969708201. DO NOT EDIT.

package vk

import "unsafe"

// CAMetalLayer: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/CAMetalLayer.html
type CAMetalLayer struct{}

// IOSurfaceRef: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/IOSurfaceRef.html
type IOSurfaceRef unsafe.Pointer

// MTLBuffer_id: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/MTLBuffer_id.html
type MTLBuffer_id unsafe.Pointer

// MTLCommandQueue_id: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/MTLCommandQueue_id.html
type MTLCommandQueue_id unsafe.Pointer

// MTLDevice_id: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/MTLDevice_id.html
type MTLDevice_id unsafe.Pointer

// MTLSharedEvent_id: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/MTLSharedEvent_id.html
type MTLSharedEvent_id unsafe.Pointer

// MTLTexture_id: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/MTLTexture_id.html
type MTLTexture_id unsafe.Pointer
