//go:build darwin
// Code generated by go-vk from vk-1.2.203.xml at 2023-03-28 13:29:28.3644511 -0500 CDT m=+3.279025701. DO NOT EDIT.

package vk

// CAMetalLayer: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/CAMetalLayer.html
type CAMetalLayer struct{}
