//go:build windows
// Code generated by go-vk from vk.xml at 2023-03-03 21:43:44.1227811 -0600 CST m=+3.717700701. DO NOT EDIT.
package vk

// Win32SurfaceCreateFlagsKHR: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkWin32SurfaceCreateFlagsKHR.html
type Win32SurfaceCreateFlagsKHR Flags
