// Code generated by go-vk from vk-1.3.246.xml at 2023-03-31 11:29:46.2587656 -0500 CDT m=+3.938778201. DO NOT EDIT.

package vk

// Win32SurfaceCreateFlagsKHR: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkWin32SurfaceCreateFlagsKHR.html
type Win32SurfaceCreateFlagsKHR Flags
