//go:build darwin
// Code generated by go-vk from vk-1.2.203.xml at 2023-03-16 13:28:32.592274 -0600 MDT m=+2.622478289. DO NOT EDIT.

package vk

// MacOSSurfaceCreateFlagsMVK: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkMacOSSurfaceCreateFlagsMVK.html
type MacOSSurfaceCreateFlagsMVK Flags
