// Code generated by go-vk from vk-1.3.242.xml at 2023-03-31 10:23:48.9774652 -0500 CDT m=+3.661265101. DO NOT EDIT.

package vk

// Win32SurfaceCreateFlagsKHR: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkWin32SurfaceCreateFlagsKHR.html
type Win32SurfaceCreateFlagsKHR Flags
