// Code generated by go-vk from vk-1.3.242.xml at 2023-03-31 10:23:49.4854149 -0500 CDT m=+4.169214801. DO NOT EDIT.

package vk

// ExportMetalObjectTypeFlagsEXT: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkExportMetalObjectTypeFlagsEXT.html
type ExportMetalObjectTypeFlagsEXT Flags

// MetalSurfaceCreateFlagsEXT: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkMetalSurfaceCreateFlagsEXT.html
type MetalSurfaceCreateFlagsEXT Flags
