// Code generated by go-vk from vk-1.3.242.xml at 2023-03-31 10:23:49.7939774 -0500 CDT m=+4.477777301. DO NOT EDIT.

package vk

// MacOSSurfaceCreateFlagsMVK: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkMacOSSurfaceCreateFlagsMVK.html
type MacOSSurfaceCreateFlagsMVK Flags
