// Code generated by go-vk from vk-1.3.246.xml at 2023-03-31 11:29:46.549792 -0500 CDT m=+4.229804601. DO NOT EDIT.

package vk

// MacOSSurfaceCreateFlagsMVK: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkMacOSSurfaceCreateFlagsMVK.html
type MacOSSurfaceCreateFlagsMVK Flags
