// Code generated by go-vk from vk.xml at 2023-01-14 10:53:48.406724 -0600 CST m=+1.098021001. DO NOT EDIT.
package vk

// AccessFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkAccessFlags.html
type AccessFlags Flags

// AttachmentDescriptionFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkAttachmentDescriptionFlags.html
type AttachmentDescriptionFlags Flags

// BufferCreateFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkBufferCreateFlags.html
type BufferCreateFlags Flags

// BufferUsageFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkBufferUsageFlags.html
type BufferUsageFlags Flags

// BufferViewCreateFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkBufferViewCreateFlags.html
type BufferViewCreateFlags Flags

// ColorComponentFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkColorComponentFlags.html
type ColorComponentFlags Flags

// CommandBufferResetFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkCommandBufferResetFlags.html
type CommandBufferResetFlags Flags

// CommandBufferUsageFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkCommandBufferUsageFlags.html
type CommandBufferUsageFlags Flags

// CommandPoolCreateFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkCommandPoolCreateFlags.html
type CommandPoolCreateFlags Flags

// CommandPoolResetFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkCommandPoolResetFlags.html
type CommandPoolResetFlags Flags

// CullModeFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkCullModeFlags.html
type CullModeFlags Flags

// DependencyFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkDependencyFlags.html
type DependencyFlags Flags

// DescriptorPoolCreateFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkDescriptorPoolCreateFlags.html
type DescriptorPoolCreateFlags Flags

// DescriptorPoolResetFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkDescriptorPoolResetFlags.html
type DescriptorPoolResetFlags Flags

// DescriptorSetLayoutCreateFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkDescriptorSetLayoutCreateFlags.html
type DescriptorSetLayoutCreateFlags Flags

// DeviceCreateFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkDeviceCreateFlags.html
type DeviceCreateFlags Flags

// DeviceQueueCreateFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkDeviceQueueCreateFlags.html
type DeviceQueueCreateFlags Flags

// EventCreateFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkEventCreateFlags.html
type EventCreateFlags Flags

// FenceCreateFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkFenceCreateFlags.html
type FenceCreateFlags Flags

// FormatFeatureFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkFormatFeatureFlags.html
type FormatFeatureFlags Flags

// FramebufferCreateFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkFramebufferCreateFlags.html
type FramebufferCreateFlags Flags

// ImageAspectFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkImageAspectFlags.html
type ImageAspectFlags Flags

// ImageCreateFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkImageCreateFlags.html
type ImageCreateFlags Flags

// ImageUsageFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkImageUsageFlags.html
type ImageUsageFlags Flags

// ImageViewCreateFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkImageViewCreateFlags.html
type ImageViewCreateFlags Flags

// InstanceCreateFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkInstanceCreateFlags.html
type InstanceCreateFlags Flags

// MemoryHeapFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkMemoryHeapFlags.html
type MemoryHeapFlags Flags

// MemoryMapFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkMemoryMapFlags.html
type MemoryMapFlags Flags

// MemoryPropertyFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkMemoryPropertyFlags.html
type MemoryPropertyFlags Flags

// PipelineCacheCreateFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkPipelineCacheCreateFlags.html
type PipelineCacheCreateFlags Flags

// PipelineColorBlendStateCreateFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkPipelineColorBlendStateCreateFlags.html
type PipelineColorBlendStateCreateFlags Flags

// PipelineCreateFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkPipelineCreateFlags.html
type PipelineCreateFlags Flags

// PipelineDepthStencilStateCreateFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkPipelineDepthStencilStateCreateFlags.html
type PipelineDepthStencilStateCreateFlags Flags

// PipelineDynamicStateCreateFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkPipelineDynamicStateCreateFlags.html
type PipelineDynamicStateCreateFlags Flags

// PipelineInputAssemblyStateCreateFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkPipelineInputAssemblyStateCreateFlags.html
type PipelineInputAssemblyStateCreateFlags Flags

// PipelineLayoutCreateFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkPipelineLayoutCreateFlags.html
type PipelineLayoutCreateFlags Flags

// PipelineMultisampleStateCreateFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkPipelineMultisampleStateCreateFlags.html
type PipelineMultisampleStateCreateFlags Flags

// PipelineRasterizationStateCreateFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkPipelineRasterizationStateCreateFlags.html
type PipelineRasterizationStateCreateFlags Flags

// PipelineShaderStageCreateFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkPipelineShaderStageCreateFlags.html
type PipelineShaderStageCreateFlags Flags

// PipelineStageFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkPipelineStageFlags.html
type PipelineStageFlags Flags

// PipelineTessellationStateCreateFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkPipelineTessellationStateCreateFlags.html
type PipelineTessellationStateCreateFlags Flags

// PipelineVertexInputStateCreateFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkPipelineVertexInputStateCreateFlags.html
type PipelineVertexInputStateCreateFlags Flags

// PipelineViewportStateCreateFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkPipelineViewportStateCreateFlags.html
type PipelineViewportStateCreateFlags Flags

// QueryControlFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkQueryControlFlags.html
type QueryControlFlags Flags

// QueryPipelineStatisticFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkQueryPipelineStatisticFlags.html
type QueryPipelineStatisticFlags Flags

// QueryPoolCreateFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkQueryPoolCreateFlags.html
type QueryPoolCreateFlags Flags

// QueryResultFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkQueryResultFlags.html
type QueryResultFlags Flags

// QueueFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkQueueFlags.html
type QueueFlags Flags

// RenderPassCreateFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkRenderPassCreateFlags.html
type RenderPassCreateFlags Flags

// SampleCountFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkSampleCountFlags.html
type SampleCountFlags Flags

// SamplerCreateFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkSamplerCreateFlags.html
type SamplerCreateFlags Flags

// SemaphoreCreateFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkSemaphoreCreateFlags.html
type SemaphoreCreateFlags Flags

// ShaderModuleCreateFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkShaderModuleCreateFlags.html
type ShaderModuleCreateFlags Flags

// ShaderStageFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkShaderStageFlags.html
type ShaderStageFlags Flags

// SparseImageFormatFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkSparseImageFormatFlags.html
type SparseImageFormatFlags Flags

// SparseMemoryBindFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkSparseMemoryBindFlags.html
type SparseMemoryBindFlags Flags

// SubpassDescriptionFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkSubpassDescriptionFlags.html
type SubpassDescriptionFlags Flags
