//go:build windows
// Code generated by go-vk from vk.xml at 2023-02-03 15:01:44.4997868 -0600 CST m=+2.509626901. DO NOT EDIT.
package vk

import (
	"unsafe"

	"golang.org/x/sys/windows"
)

const (
	keyvkAcquireFullScreenExclusiveModeEXT vkCommandKey = iota + 441
	keyvkAcquireWinrtDisplayNV
	keyvkCreateWin32SurfaceKHR
	keyvkGetDeviceGroupSurfacePresentModes2EXT
	keyvkGetFenceWin32HandleKHR
	keyvkGetMemoryWin32HandleKHR
	keyvkGetMemoryWin32HandleNV
	keyvkGetMemoryWin32HandlePropertiesKHR
	keyvkGetPhysicalDeviceSurfacePresentModes2EXT
	keyvkGetPhysicalDeviceWin32PresentationSupportKHR
	keyvkGetSemaphoreWin32HandleKHR
	keyvkGetWinrtDisplayNV
	keyvkImportFenceWin32HandleKHR
	keyvkImportSemaphoreWin32HandleKHR
	keyvkReleaseFullScreenExclusiveModeEXT
)

func init() {
	lazyCommands[keyvkAcquireFullScreenExclusiveModeEXT] = vkCommand{"vkAcquireFullScreenExclusiveModeEXT", 2, true, nil}
	lazyCommands[keyvkAcquireWinrtDisplayNV] = vkCommand{"vkAcquireWinrtDisplayNV", 2, true, nil}
	lazyCommands[keyvkCreateWin32SurfaceKHR] = vkCommand{"vkCreateWin32SurfaceKHR", 4, true, nil}
	lazyCommands[keyvkGetDeviceGroupSurfacePresentModes2EXT] = vkCommand{"vkGetDeviceGroupSurfacePresentModes2EXT", 3, true, nil}
	lazyCommands[keyvkGetFenceWin32HandleKHR] = vkCommand{"vkGetFenceWin32HandleKHR", 3, true, nil}
	lazyCommands[keyvkGetMemoryWin32HandleKHR] = vkCommand{"vkGetMemoryWin32HandleKHR", 3, true, nil}
	lazyCommands[keyvkGetMemoryWin32HandleNV] = vkCommand{"vkGetMemoryWin32HandleNV", 4, true, nil}
	lazyCommands[keyvkGetMemoryWin32HandlePropertiesKHR] = vkCommand{"vkGetMemoryWin32HandlePropertiesKHR", 4, true, nil}
	lazyCommands[keyvkGetPhysicalDeviceSurfacePresentModes2EXT] = vkCommand{"vkGetPhysicalDeviceSurfacePresentModes2EXT", 4, true, nil}
	lazyCommands[keyvkGetPhysicalDeviceWin32PresentationSupportKHR] = vkCommand{"vkGetPhysicalDeviceWin32PresentationSupportKHR", 2, true, nil}
	lazyCommands[keyvkGetSemaphoreWin32HandleKHR] = vkCommand{"vkGetSemaphoreWin32HandleKHR", 3, true, nil}
	lazyCommands[keyvkGetWinrtDisplayNV] = vkCommand{"vkGetWinrtDisplayNV", 3, true, nil}
	lazyCommands[keyvkImportFenceWin32HandleKHR] = vkCommand{"vkImportFenceWin32HandleKHR", 2, true, nil}
	lazyCommands[keyvkImportSemaphoreWin32HandleKHR] = vkCommand{"vkImportSemaphoreWin32HandleKHR", 2, true, nil}
	lazyCommands[keyvkReleaseFullScreenExclusiveModeEXT] = vkCommand{"vkReleaseFullScreenExclusiveModeEXT", 2, true, nil}
}

// AcquireFullScreenExclusiveModeEXT: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/vkAcquireFullScreenExclusiveModeEXT.html
func AcquireFullScreenExclusiveModeEXT(device Device, swapchain SwapchainKHR) (r Result) {

	r = Result(execTrampoline(keyvkAcquireFullScreenExclusiveModeEXT, uintptr(device), uintptr(swapchain)))

	return
}

// AcquireWinrtDisplayNV: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/vkAcquireWinrtDisplayNV.html
func AcquireWinrtDisplayNV(physicalDevice PhysicalDevice, display DisplayKHR) (r Result) {

	r = Result(execTrampoline(keyvkAcquireWinrtDisplayNV, uintptr(physicalDevice), uintptr(display)))

	return
}

// CreateWin32SurfaceKHR: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/vkCreateWin32SurfaceKHR.html
func CreateWin32SurfaceKHR(instance Instance, createInfo *Win32SurfaceCreateInfoKHR, allocator *AllocationCallbacks) (r Result, surface SurfaceKHR) {
	// Parameter is a singular input, requires translation - createInfo
	var pCreateInfo *_vkWin32SurfaceCreateInfoKHR
	if createInfo != nil {
		pCreateInfo = createInfo.Vulkanize()
	}

	// Parameter is a singular input, pass direct - allocator
	var pAllocator unsafe.Pointer
	if allocator != nil {
		pAllocator = unsafe.Pointer(allocator)
	}

	// surface is a binding-allocated single return value and will be populated by Vulkan
	ptr_pSurface := &surface

	r = Result(execTrampoline(keyvkCreateWin32SurfaceKHR, uintptr(instance), uintptr(unsafe.Pointer(pCreateInfo)), uintptr(unsafe.Pointer(pAllocator)), uintptr(unsafe.Pointer(ptr_pSurface))))

	return
}

// GetDeviceGroupSurfacePresentModes2EXT: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/vkGetDeviceGroupSurfacePresentModes2EXT.html
func GetDeviceGroupSurfacePresentModes2EXT(device Device, surfaceInfo *PhysicalDeviceSurfaceInfo2KHR) (r Result, modes DeviceGroupPresentModeFlagsKHR) {
	// Parameter is a singular input, requires translation - surfaceInfo
	var pSurfaceInfo *_vkPhysicalDeviceSurfaceInfo2KHR
	if surfaceInfo != nil {
		pSurfaceInfo = surfaceInfo.Vulkanize()
	}

	// modes is a binding-allocated single return value and will be populated by Vulkan
	ptr_pModes := &modes

	r = Result(execTrampoline(keyvkGetDeviceGroupSurfacePresentModes2EXT, uintptr(device), uintptr(unsafe.Pointer(pSurfaceInfo)), uintptr(unsafe.Pointer(ptr_pModes))))

	return
}

// GetFenceWin32HandleKHR: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/vkGetFenceWin32HandleKHR.html
func GetFenceWin32HandleKHR(device Device, getWin32HandleInfo *FenceGetWin32HandleInfoKHR) (r Result, handle windows.Handle) {
	// Parameter is a singular input, requires translation - getWin32HandleInfo
	var pGetWin32HandleInfo *_vkFenceGetWin32HandleInfoKHR
	if getWin32HandleInfo != nil {
		pGetWin32HandleInfo = getWin32HandleInfo.Vulkanize()
	}

	// handle is a binding-allocated single return value and will be populated by Vulkan
	ptr_pHandle := &handle

	r = Result(execTrampoline(keyvkGetFenceWin32HandleKHR, uintptr(device), uintptr(unsafe.Pointer(pGetWin32HandleInfo)), uintptr(unsafe.Pointer(ptr_pHandle))))

	return
}

// GetMemoryWin32HandleKHR: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/vkGetMemoryWin32HandleKHR.html
func GetMemoryWin32HandleKHR(device Device, getWin32HandleInfo *MemoryGetWin32HandleInfoKHR) (r Result, handle windows.Handle) {
	// Parameter is a singular input, requires translation - getWin32HandleInfo
	var pGetWin32HandleInfo *_vkMemoryGetWin32HandleInfoKHR
	if getWin32HandleInfo != nil {
		pGetWin32HandleInfo = getWin32HandleInfo.Vulkanize()
	}

	// handle is a binding-allocated single return value and will be populated by Vulkan
	ptr_pHandle := &handle

	r = Result(execTrampoline(keyvkGetMemoryWin32HandleKHR, uintptr(device), uintptr(unsafe.Pointer(pGetWin32HandleInfo)), uintptr(unsafe.Pointer(ptr_pHandle))))

	return
}

// GetMemoryWin32HandleNV: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/vkGetMemoryWin32HandleNV.html
func GetMemoryWin32HandleNV(device Device, memory DeviceMemory, handleType ExternalMemoryHandleTypeFlagsNV) (r Result, handle windows.Handle) {
	// handle is a binding-allocated single return value and will be populated by Vulkan
	ptr_pHandle := &handle

	r = Result(execTrampoline(keyvkGetMemoryWin32HandleNV, uintptr(device), uintptr(memory), uintptr(handleType), uintptr(unsafe.Pointer(ptr_pHandle))))

	return
}

// GetMemoryWin32HandlePropertiesKHR: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/vkGetMemoryWin32HandlePropertiesKHR.html
func GetMemoryWin32HandlePropertiesKHR(device Device, handleType ExternalMemoryHandleTypeFlagBits, handle windows.Handle) (r Result, memoryWin32HandleProperties MemoryWin32HandlePropertiesKHR) {
	// memoryWin32HandleProperties is a binding-allocated single return value and will be populated by Vulkan, but requiring translation
	var pMemoryWin32HandleProperties _vkMemoryWin32HandlePropertiesKHR
	ptr_pMemoryWin32HandleProperties := &pMemoryWin32HandleProperties

	r = Result(execTrampoline(keyvkGetMemoryWin32HandlePropertiesKHR, uintptr(device), uintptr(handleType), uintptr(handle), uintptr(unsafe.Pointer(ptr_pMemoryWin32HandleProperties))))

	memoryWin32HandleProperties = *(pMemoryWin32HandleProperties.Goify())
	return
}

// GetPhysicalDeviceSurfacePresentModes2EXT: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/vkGetPhysicalDeviceSurfacePresentModes2EXT.html
func GetPhysicalDeviceSurfacePresentModes2EXT(physicalDevice PhysicalDevice, surfaceInfo *PhysicalDeviceSurfaceInfo2KHR) (r Result, presentModes []PresentModeKHR) {
	// Parameter is a singular input, requires translation - surfaceInfo
	var pSurfaceInfo *_vkPhysicalDeviceSurfaceInfo2KHR
	if surfaceInfo != nil {
		pSurfaceInfo = surfaceInfo.Vulkanize()
	}

	// presentModes is a double-call array output
	var presentModeCount uint32
	pPresentModeCount := &presentModeCount
	// first trampoline happens here; also, still need to check returned Result value
	// NOT identical internal and external, result needs translation
	var pPresentModes *PresentModeKHR

	r = Result(execTrampoline(keyvkGetPhysicalDeviceSurfacePresentModes2EXT, uintptr(physicalDevice), uintptr(unsafe.Pointer(pSurfaceInfo)), uintptr(unsafe.Pointer(pPresentModeCount)), uintptr(unsafe.Pointer(pPresentModes))))

	sl_pPresentModes := make([]PresentModeKHR, presentModeCount)
	presentModes = make([]PresentModeKHR, presentModeCount)
	pPresentModes = &sl_pPresentModes[0]

	// Trampoline call after last array allocation
	r = Result(execTrampoline(keyvkGetPhysicalDeviceSurfacePresentModes2EXT, uintptr(physicalDevice), uintptr(unsafe.Pointer(pSurfaceInfo)), uintptr(unsafe.Pointer(pPresentModeCount)), uintptr(unsafe.Pointer(pPresentModes))))

	for i := range sl_pPresentModes {
		presentModes[i] = *&sl_pPresentModes[i]
	}
	return
}

// GetPhysicalDeviceWin32PresentationSupportKHR: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/vkGetPhysicalDeviceWin32PresentationSupportKHR.html
func GetPhysicalDeviceWin32PresentationSupportKHR(physicalDevice PhysicalDevice, queueFamilyIndex uint32) (r bool) {

	rval := Bool32(execTrampoline(keyvkGetPhysicalDeviceWin32PresentationSupportKHR, uintptr(physicalDevice), uintptr(queueFamilyIndex)))
	r = translatePublic_Bool32(rval)

	return
}

// GetSemaphoreWin32HandleKHR: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/vkGetSemaphoreWin32HandleKHR.html
func GetSemaphoreWin32HandleKHR(device Device, getWin32HandleInfo *SemaphoreGetWin32HandleInfoKHR) (r Result, handle windows.Handle) {
	// Parameter is a singular input, requires translation - getWin32HandleInfo
	var pGetWin32HandleInfo *_vkSemaphoreGetWin32HandleInfoKHR
	if getWin32HandleInfo != nil {
		pGetWin32HandleInfo = getWin32HandleInfo.Vulkanize()
	}

	// handle is a binding-allocated single return value and will be populated by Vulkan
	ptr_pHandle := &handle

	r = Result(execTrampoline(keyvkGetSemaphoreWin32HandleKHR, uintptr(device), uintptr(unsafe.Pointer(pGetWin32HandleInfo)), uintptr(unsafe.Pointer(ptr_pHandle))))

	return
}

// GetWinrtDisplayNV: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/vkGetWinrtDisplayNV.html
func GetWinrtDisplayNV(physicalDevice PhysicalDevice, deviceRelativeId uint32) (r Result, display DisplayKHR) {
	// display is a binding-allocated single return value and will be populated by Vulkan
	ptr_pDisplay := &display

	r = Result(execTrampoline(keyvkGetWinrtDisplayNV, uintptr(physicalDevice), uintptr(deviceRelativeId), uintptr(unsafe.Pointer(ptr_pDisplay))))

	return
}

// ImportFenceWin32HandleKHR: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/vkImportFenceWin32HandleKHR.html
func ImportFenceWin32HandleKHR(device Device, importFenceWin32HandleInfo *ImportFenceWin32HandleInfoKHR) (r Result) {
	// Parameter is a singular input, requires translation - importFenceWin32HandleInfo
	var pImportFenceWin32HandleInfo *_vkImportFenceWin32HandleInfoKHR
	if importFenceWin32HandleInfo != nil {
		pImportFenceWin32HandleInfo = importFenceWin32HandleInfo.Vulkanize()
	}

	r = Result(execTrampoline(keyvkImportFenceWin32HandleKHR, uintptr(device), uintptr(unsafe.Pointer(pImportFenceWin32HandleInfo))))

	return
}

// ImportSemaphoreWin32HandleKHR: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/vkImportSemaphoreWin32HandleKHR.html
func ImportSemaphoreWin32HandleKHR(device Device, importSemaphoreWin32HandleInfo *ImportSemaphoreWin32HandleInfoKHR) (r Result) {
	// Parameter is a singular input, requires translation - importSemaphoreWin32HandleInfo
	var pImportSemaphoreWin32HandleInfo *_vkImportSemaphoreWin32HandleInfoKHR
	if importSemaphoreWin32HandleInfo != nil {
		pImportSemaphoreWin32HandleInfo = importSemaphoreWin32HandleInfo.Vulkanize()
	}

	r = Result(execTrampoline(keyvkImportSemaphoreWin32HandleKHR, uintptr(device), uintptr(unsafe.Pointer(pImportSemaphoreWin32HandleInfo))))

	return
}

// ReleaseFullScreenExclusiveModeEXT: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/vkReleaseFullScreenExclusiveModeEXT.html
func ReleaseFullScreenExclusiveModeEXT(device Device, swapchain SwapchainKHR) (r Result) {

	r = Result(execTrampoline(keyvkReleaseFullScreenExclusiveModeEXT, uintptr(device), uintptr(swapchain)))

	return
}
