//go:build darwin
// Code generated by go-vk from vk-1.2.203.xml at 2023-03-16 13:28:32.124259 -0600 MDT m=+2.154466115. DO NOT EDIT.

package vk

// Platform-specific values for VkStructureType
const (
	STRUCTURE_TYPE_METAL_SURFACE_CREATE_INFO_EXT StructureType = 1000217000
)
