// Code generated by go-vk from vk-1.3.246.xml at 2023-03-31 11:29:46.4893755 -0500 CDT m=+4.169388101. DO NOT EDIT.

package vk

// Platform-specific values for VkStructureType
const (
	STRUCTURE_TYPE_MACOS_SURFACE_CREATE_INFO_MVK StructureType = 1000123000
)
