// Code generated by go-vk from vk-1.3.242.xml at 2023-03-31 10:23:50.1148313 -0500 CDT m=+4.798631201. DO NOT EDIT.

package vk

// Platform-specific values for VkStructureType
const (
	STRUCTURE_TYPE_MACOS_SURFACE_CREATE_INFO_MVK StructureType = 1000123000
)
