// Code generated by go-vk from vk-1.2.203.xml at 2023-03-28 13:29:27.6081199 -0500 CDT m=+2.522694501. DO NOT EDIT.

package vk

// Platform-specific values for VkStructureType
const (
	STRUCTURE_TYPE_MACOS_SURFACE_CREATE_INFO_MVK StructureType = 1000123000
)
