// Code generated by "stringer -output=enum_string_7.go -type=VideoComponentBitDepthFlagBitsKHR,VideoDecodeCapabilityFlagBitsKHR,VideoDecodeH264PictureLayoutFlagBitsKHR,VideoDecodeUsageFlagBitsKHR,VideoSessionCreateFlagBitsKHR,ViewportCoordinateSwizzleNV"; DO NOT EDIT.

package vk

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VIDEO_COMPONENT_BIT_DEPTH_INVALID_KHR-0]
	_ = x[VIDEO_COMPONENT_BIT_DEPTH_8_BIT_KHR-1]
	_ = x[VIDEO_COMPONENT_BIT_DEPTH_10_BIT_KHR-4]
	_ = x[VIDEO_COMPONENT_BIT_DEPTH_12_BIT_KHR-16]
}

const (
	_VideoComponentBitDepthFlagBitsKHR_name_0 = "VIDEO_COMPONENT_BIT_DEPTH_INVALID_KHRVIDEO_COMPONENT_BIT_DEPTH_8_BIT_KHR"
	_VideoComponentBitDepthFlagBitsKHR_name_1 = "VIDEO_COMPONENT_BIT_DEPTH_10_BIT_KHR"
	_VideoComponentBitDepthFlagBitsKHR_name_2 = "VIDEO_COMPONENT_BIT_DEPTH_12_BIT_KHR"
)

var (
	_VideoComponentBitDepthFlagBitsKHR_index_0 = [...]uint8{0, 37, 72}
)

func (i VideoComponentBitDepthFlagBitsKHR) String() string {
	switch {
	case i <= 1:
		return _VideoComponentBitDepthFlagBitsKHR_name_0[_VideoComponentBitDepthFlagBitsKHR_index_0[i]:_VideoComponentBitDepthFlagBitsKHR_index_0[i+1]]
	case i == 4:
		return _VideoComponentBitDepthFlagBitsKHR_name_1
	case i == 16:
		return _VideoComponentBitDepthFlagBitsKHR_name_2
	default:
		return "VideoComponentBitDepthFlagBitsKHR(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VIDEO_DECODE_CAPABILITY_DPB_AND_OUTPUT_COINCIDE_BIT_KHR-1]
	_ = x[VIDEO_DECODE_CAPABILITY_DPB_AND_OUTPUT_DISTINCT_BIT_KHR-2]
}

const _VideoDecodeCapabilityFlagBitsKHR_name = "VIDEO_DECODE_CAPABILITY_DPB_AND_OUTPUT_COINCIDE_BIT_KHRVIDEO_DECODE_CAPABILITY_DPB_AND_OUTPUT_DISTINCT_BIT_KHR"

var _VideoDecodeCapabilityFlagBitsKHR_index = [...]uint8{0, 55, 110}

func (i VideoDecodeCapabilityFlagBitsKHR) String() string {
	i -= 1
	if i >= VideoDecodeCapabilityFlagBitsKHR(len(_VideoDecodeCapabilityFlagBitsKHR_index)-1) {
		return "VideoDecodeCapabilityFlagBitsKHR(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _VideoDecodeCapabilityFlagBitsKHR_name[_VideoDecodeCapabilityFlagBitsKHR_index[i]:_VideoDecodeCapabilityFlagBitsKHR_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VIDEO_DECODE_H264_PICTURE_LAYOUT_PROGRESSIVE_KHR-0]
	_ = x[VIDEO_DECODE_H264_PICTURE_LAYOUT_INTERLACED_INTERLEAVED_LINES_BIT_KHR-1]
	_ = x[VIDEO_DECODE_H264_PICTURE_LAYOUT_INTERLACED_SEPARATE_PLANES_BIT_KHR-2]
}

const _VideoDecodeH264PictureLayoutFlagBitsKHR_name = "VIDEO_DECODE_H264_PICTURE_LAYOUT_PROGRESSIVE_KHRVIDEO_DECODE_H264_PICTURE_LAYOUT_INTERLACED_INTERLEAVED_LINES_BIT_KHRVIDEO_DECODE_H264_PICTURE_LAYOUT_INTERLACED_SEPARATE_PLANES_BIT_KHR"

var _VideoDecodeH264PictureLayoutFlagBitsKHR_index = [...]uint8{0, 48, 117, 184}

func (i VideoDecodeH264PictureLayoutFlagBitsKHR) String() string {
	if i >= VideoDecodeH264PictureLayoutFlagBitsKHR(len(_VideoDecodeH264PictureLayoutFlagBitsKHR_index)-1) {
		return "VideoDecodeH264PictureLayoutFlagBitsKHR(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _VideoDecodeH264PictureLayoutFlagBitsKHR_name[_VideoDecodeH264PictureLayoutFlagBitsKHR_index[i]:_VideoDecodeH264PictureLayoutFlagBitsKHR_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VIDEO_DECODE_USAGE_DEFAULT_KHR-0]
	_ = x[VIDEO_DECODE_USAGE_TRANSCODING_BIT_KHR-1]
	_ = x[VIDEO_DECODE_USAGE_OFFLINE_BIT_KHR-2]
	_ = x[VIDEO_DECODE_USAGE_STREAMING_BIT_KHR-4]
}

const (
	_VideoDecodeUsageFlagBitsKHR_name_0 = "VIDEO_DECODE_USAGE_DEFAULT_KHRVIDEO_DECODE_USAGE_TRANSCODING_BIT_KHRVIDEO_DECODE_USAGE_OFFLINE_BIT_KHR"
	_VideoDecodeUsageFlagBitsKHR_name_1 = "VIDEO_DECODE_USAGE_STREAMING_BIT_KHR"
)

var (
	_VideoDecodeUsageFlagBitsKHR_index_0 = [...]uint8{0, 30, 68, 102}
)

func (i VideoDecodeUsageFlagBitsKHR) String() string {
	switch {
	case i <= 2:
		return _VideoDecodeUsageFlagBitsKHR_name_0[_VideoDecodeUsageFlagBitsKHR_index_0[i]:_VideoDecodeUsageFlagBitsKHR_index_0[i+1]]
	case i == 4:
		return _VideoDecodeUsageFlagBitsKHR_name_1
	default:
		return "VideoDecodeUsageFlagBitsKHR(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VIDEO_SESSION_CREATE_PROTECTED_CONTENT_BIT_KHR-1]
}

const _VideoSessionCreateFlagBitsKHR_name = "VIDEO_SESSION_CREATE_PROTECTED_CONTENT_BIT_KHR"

var _VideoSessionCreateFlagBitsKHR_index = [...]uint8{0, 46}

func (i VideoSessionCreateFlagBitsKHR) String() string {
	i -= 1
	if i >= VideoSessionCreateFlagBitsKHR(len(_VideoSessionCreateFlagBitsKHR_index)-1) {
		return "VideoSessionCreateFlagBitsKHR(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _VideoSessionCreateFlagBitsKHR_name[_VideoSessionCreateFlagBitsKHR_index[i]:_VideoSessionCreateFlagBitsKHR_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VIEWPORT_COORDINATE_SWIZZLE_POSITIVE_X_NV-0]
	_ = x[VIEWPORT_COORDINATE_SWIZZLE_NEGATIVE_X_NV-1]
	_ = x[VIEWPORT_COORDINATE_SWIZZLE_POSITIVE_Y_NV-2]
	_ = x[VIEWPORT_COORDINATE_SWIZZLE_NEGATIVE_Y_NV-3]
	_ = x[VIEWPORT_COORDINATE_SWIZZLE_POSITIVE_Z_NV-4]
	_ = x[VIEWPORT_COORDINATE_SWIZZLE_NEGATIVE_Z_NV-5]
	_ = x[VIEWPORT_COORDINATE_SWIZZLE_POSITIVE_W_NV-6]
	_ = x[VIEWPORT_COORDINATE_SWIZZLE_NEGATIVE_W_NV-7]
}

const _ViewportCoordinateSwizzleNV_name = "VIEWPORT_COORDINATE_SWIZZLE_POSITIVE_X_NVVIEWPORT_COORDINATE_SWIZZLE_NEGATIVE_X_NVVIEWPORT_COORDINATE_SWIZZLE_POSITIVE_Y_NVVIEWPORT_COORDINATE_SWIZZLE_NEGATIVE_Y_NVVIEWPORT_COORDINATE_SWIZZLE_POSITIVE_Z_NVVIEWPORT_COORDINATE_SWIZZLE_NEGATIVE_Z_NVVIEWPORT_COORDINATE_SWIZZLE_POSITIVE_W_NVVIEWPORT_COORDINATE_SWIZZLE_NEGATIVE_W_NV"

var _ViewportCoordinateSwizzleNV_index = [...]uint16{0, 41, 82, 123, 164, 205, 246, 287, 328}

func (i ViewportCoordinateSwizzleNV) String() string {
	if i < 0 || i >= ViewportCoordinateSwizzleNV(len(_ViewportCoordinateSwizzleNV_index)-1) {
		return "ViewportCoordinateSwizzleNV(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ViewportCoordinateSwizzleNV_name[_ViewportCoordinateSwizzleNV_index[i]:_ViewportCoordinateSwizzleNV_index[i+1]]
}
