// Code generated by go-vk from vk-1.2.203.xml at 2023-03-28 13:29:28.2738145 -0500 CDT m=+3.188389101. DO NOT EDIT.

package vk

// Platform-specific values for VkStructureType
const (
	STRUCTURE_TYPE_METAL_SURFACE_CREATE_INFO_EXT StructureType = 1000217000
)
