//go:build darwin
// Code generated by go-vk from vk-1.2.203.xml at 2023-03-28 13:29:27.6388747 -0500 CDT m=+2.553449301. DO NOT EDIT.

package vk

// Extension names and versions
const (
	MVK_MACOS_SURFACE_EXTENSION_NAME = "VK_MVK_macos_surface"
	MVK_MACOS_SURFACE_SPEC_VERSION   = 3
)
