//go:build darwin
// Code generated by go-vk from vk-1.2.203.xml at 2023-03-28 13:29:28.3176783 -0500 CDT m=+3.232252901. DO NOT EDIT.

package vk

// Extension names and versions
const (
	EXT_METAL_SURFACE_EXTENSION_NAME = "VK_EXT_metal_surface"
	EXT_METAL_SURFACE_SPEC_VERSION   = 1
)
