//go:build darwin
// Code generated by go-vk from vk-1.3.246.xml at 2023-03-31 11:29:46.7658446 -0500 CDT m=+4.445857201. DO NOT EDIT.

package vk

// Extension names and versions
const (
	EXT_METAL_OBJECTS_EXTENSION_NAME = "VK_EXT_metal_objects"
	EXT_METAL_OBJECTS_SPEC_VERSION   = 1
	EXT_METAL_SURFACE_EXTENSION_NAME = "VK_EXT_metal_surface"
	EXT_METAL_SURFACE_SPEC_VERSION   = 1
)
