// Code generated by go-vk from vk.xml at 2023-03-09 10:07:56.7816076 -0600 CST m=+2.190229301. DO NOT EDIT.

package vk

// Extension names and versions
const (
	EXT_TRANSFORM_FEEDBACK_SPEC_VERSION = 1
)
