//go:build darwin
// Code generated by go-vk from vk-1.2.203.xml at 2023-03-16 13:28:32.576719 -0600 MDT m=+2.606923286. DO NOT EDIT.

package vk

// Extension names and versions
const (
	MVK_MACOS_SURFACE_EXTENSION_NAME = "VK_MVK_macos_surface"
	MVK_MACOS_SURFACE_SPEC_VERSION   = 3
)
