//go:build darwin
// Code generated by go-vk from vk-1.3.242.xml at 2023-03-31 10:23:50.1641259 -0500 CDT m=+4.847925801. DO NOT EDIT.

package vk

// Extension names and versions
const (
	MVK_MACOS_SURFACE_EXTENSION_NAME = "VK_MVK_macos_surface"
	MVK_MACOS_SURFACE_SPEC_VERSION   = 3
)
