// Code generated by go-vk from vk.xml at 2023-01-14 15:10:03.4462985 -0600 CST m=+1.339742701. DO NOT EDIT.
package vk

// Buffer: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkBuffer.html
type Buffer nonDispatchableHandle

// BufferView: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkBufferView.html
type BufferView nonDispatchableHandle

// CommandBuffer: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkCommandBuffer.html
type CommandBuffer handle

// CommandPool: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkCommandPool.html
type CommandPool nonDispatchableHandle

// DescriptorPool: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkDescriptorPool.html
type DescriptorPool nonDispatchableHandle

// DescriptorSet: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkDescriptorSet.html
type DescriptorSet nonDispatchableHandle

// DescriptorSetLayout: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkDescriptorSetLayout.html
type DescriptorSetLayout nonDispatchableHandle

// DescriptorUpdateTemplate: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkDescriptorUpdateTemplate.html
type DescriptorUpdateTemplate nonDispatchableHandle

// Device: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkDevice.html
type Device handle

// DeviceMemory: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkDeviceMemory.html
type DeviceMemory nonDispatchableHandle

// Event: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkEvent.html
type Event nonDispatchableHandle

// Fence: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkFence.html
type Fence nonDispatchableHandle

// Framebuffer: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkFramebuffer.html
type Framebuffer nonDispatchableHandle

// Image: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkImage.html
type Image nonDispatchableHandle

// ImageView: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkImageView.html
type ImageView nonDispatchableHandle

// Instance: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkInstance.html
type Instance handle

// PhysicalDevice: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkPhysicalDevice.html
type PhysicalDevice handle

// Pipeline: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkPipeline.html
type Pipeline nonDispatchableHandle

// PipelineCache: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkPipelineCache.html
type PipelineCache nonDispatchableHandle

// PipelineLayout: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkPipelineLayout.html
type PipelineLayout nonDispatchableHandle

// QueryPool: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkQueryPool.html
type QueryPool nonDispatchableHandle

// Queue: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkQueue.html
type Queue handle

// RenderPass: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkRenderPass.html
type RenderPass nonDispatchableHandle

// Sampler: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkSampler.html
type Sampler nonDispatchableHandle

// SamplerYcbcrConversion: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkSamplerYcbcrConversion.html
type SamplerYcbcrConversion nonDispatchableHandle

// Semaphore: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkSemaphore.html
type Semaphore nonDispatchableHandle

// ShaderModule: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkShaderModule.html
type ShaderModule nonDispatchableHandle

// SurfaceKHR: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkSurfaceKHR.html
type SurfaceKHR nonDispatchableHandle

// handle: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VK_DEFINE_HANDLE.html
type handle uintptr

// nonDispatchableHandle: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VK_DEFINE_NON_DISPATCHABLE_HANDLE.html
type nonDispatchableHandle uint64
