//go:build darwin
// Code generated by go-vk from vk-1.2.203.xml at 2023-03-28 13:29:28.0573521 -0500 CDT m=+2.971926701. DO NOT EDIT.

package vk

import "unsafe"

// MetalSurfaceCreateInfoEXT: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkMetalSurfaceCreateInfoEXT.html
type MetalSurfaceCreateInfoEXT struct {
	// SType = STRUCTURE_TYPE_METAL_SURFACE_CREATE_INFO_EXT
	PNext  unsafe.Pointer
	Flags  MetalSurfaceCreateFlagsEXT
	PLayer *CAMetalLayer
}

type _vkMetalSurfaceCreateInfoEXT struct {
	sType  StructureType
	pNext  unsafe.Pointer
	flags  MetalSurfaceCreateFlagsEXT
	pLayer *CAMetalLayer
}

func (s *_vkMetalSurfaceCreateInfoEXT) Goify() *MetalSurfaceCreateInfoEXT {
	rval := &MetalSurfaceCreateInfoEXT{
		PNext:  (unsafe.Pointer)(s.pNext),
		Flags:  (MetalSurfaceCreateFlagsEXT)(s.flags),
		PLayer: (*CAMetalLayer)(s.pLayer),
	}
	return rval
}
func (s *MetalSurfaceCreateInfoEXT) Vulkanize() *_vkMetalSurfaceCreateInfoEXT {
	if s == nil {
		return nil
	}
	rval := &_vkMetalSurfaceCreateInfoEXT{
		sType:  STRUCTURE_TYPE_METAL_SURFACE_CREATE_INFO_EXT, /*c1*/
		pNext:  (unsafe.Pointer)(s.PNext),                    /*cb*/
		flags:  (MetalSurfaceCreateFlagsEXT)(s.Flags),        /*cb*/
		pLayer: (*CAMetalLayer)(s.PLayer),                    /*cb*/
	}
	return rval
}
